# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db80870987e961e53109f26815f7ed6d4d35b6d684edfdf19a58cf4e8b15bae8d1f5d0f106a7d8c2a1aa7c7853554b6ba4d5f78929ef7a3f341f4e9ccd2ab8f6

test:
  secret_key_base: f6c5171b2a6b27582f4b500fbdb601fae43bf0e45f88ef1309dfabd6af6ab23d081e604243dc7b00c27e9f2475c7c6a70e8dd0c23690cdab0b5b966778b83369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
